### ISSUE TITLE
Fix some bugs

### ISSUE THREAD

**Issue by AbdelrhmanX7** [AhmedHenawy11/simple_shell#1]
You don't need to write a unit test if you have removed all files from your project. This will make your repository cleaner.

**Comment by AhmedHenawy11** [comment]
> You don't need to write a unit test if you have removed all files from your project. This will make your repository cleaner.

Thanks my friend, Still building my project  , i'll remove irrelevant tests

**Comment by AbdelrhmanX7** [comment]
bro i am just kidding keep doing a good job
